"""Add UserWatchlist and WatchlistStock models, update User relationships

Revision ID: 4988d12f87e6
Revises: 2f65d36967c1
Create Date: 2025-10-18 16:24:23.262009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4988d12f87e6'
down_revision: Union[str, None] = '2f65d36967c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_watchlists_id'), 'user_watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_user_watchlists_name'), 'user_watchlists', ['name'], unique=False)
    op.create_table('watchlist_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['watchlist_id'], ['user_watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_stocks_id'), 'watchlist_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_stocks_symbol'), 'watchlist_stocks', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_stocks_symbol'), table_name='watchlist_stocks')
    op.drop_index(op.f('ix_watchlist_stocks_id'), table_name='watchlist_stocks')
    op.drop_table('watchlist_stocks')
    op.drop_index(op.f('ix_user_watchlists_name'), table_name='user_watchlists')
    op.drop_index(op.f('ix_user_watchlists_id'), table_name='user_watchlists')
    op.drop_table('user_watchlists')
    # ### end Alembic commands ###
