"""Create trading_leaderboard_snapshots table

Revision ID: 7ec6e7ce263a
Revises: f8e8120162e3
Create Date: 2025-10-22 17:17:57.086903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ec6e7ce263a'
down_revision: Union[str, None] = 'f8e8120162e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'trading_leaderboard_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('student_id', sa.Integer(), nullable=True),
        sa.Column('student_full_name', sa.String(), nullable=True),
        sa.Column('student_email', sa.String(), nullable=True),
        sa.Column('starting_capital', sa.Float(), nullable=True),
        sa.Column('current_balance', sa.Float(), nullable=True),
        sa.Column('trading_profit', sa.Float(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trading_leaderboard_snapshots_id'), 'trading_leaderboard_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_trading_leaderboard_snapshots_student_id'), 'trading_leaderboard_snapshots', ['student_id'], unique=False)
    op.create_index(op.f('ix_trading_leaderboard_snapshots_student_full_name'), 'trading_leaderboard_snapshots', ['student_full_name'], unique=False)
    op.create_index(op.f('ix_trading_leaderboard_snapshots_student_email'), 'trading_leaderboard_snapshots', ['student_email'], unique=False)
    op.create_index(op.f('ix_trading_leaderboard_snapshots_trading_profit'), 'trading_leaderboard_snapshots', ['trading_profit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_leaderboard_snapshots_trading_profit'), table_name='trading_leaderboard_snapshots')
    op.drop_index(op.f('ix_trading_leaderboard_snapshots_student_email'), table_name='trading_leaderboard_snapshots')
    op.drop_index(op.f('ix_trading_leaderboard_snapshots_student_full_name'), table_name='trading_leaderboard_snapshots')
    op.drop_index(op.f('ix_trading_leaderboard_snapshots_student_id'), table_name='trading_leaderboard_snapshots')
    op.drop_index(op.f('ix_trading_leaderboard_snapshots_id'), table_name='trading_leaderboard_snapshots')
    op.drop_table('trading_leaderboard_snapshots')
    # ### end Alembic commands ###
