"""Add LeaderboardSnapshot table

Revision ID: b25b129c919f
Revises: fd80e7d61a3e
Create Date: 2025-10-24 08:28:05.465783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b25b129c919f'
down_revision: Union[str, None] = 'fd80e7d61a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_full_name', sa.String(), nullable=True),
    sa.Column('student_email', sa.String(), nullable=True),
    sa.Column('lessons_completed', sa.Integer(), nullable=True),
    sa.Column('accumulated_exam_score', sa.Float(), nullable=True),
    sa.Column('total_rewards', sa.Integer(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_snapshots_id'), 'leaderboard_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_school_id'), 'leaderboard_snapshots', ['school_id'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_student_email'), 'leaderboard_snapshots', ['student_email'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_student_full_name'), 'leaderboard_snapshots', ['student_full_name'], unique=False)
    op.create_index(op.f('ix_leaderboard_snapshots_student_id'), 'leaderboard_snapshots', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaderboard_snapshots_student_id'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_student_full_name'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_student_email'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_school_id'), table_name='leaderboard_snapshots')
    op.drop_index(op.f('ix_leaderboard_snapshots_id'), table_name='leaderboard_snapshots')
    op.drop_table('leaderboard_snapshots')
    # ### end Alembic commands ###
