"""Add total_amount to TradeOrder model

Revision ID: b9c77ca5d2fb
Revises: 4988d12f87e6
Create Date: 2025-10-18 19:29:49.743582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9c77ca5d2fb'
down_revision: Union[str, None] = '4988d12f87e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_orders', sa.Column('total_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_orders', 'total_amount')
    # ### end Alembic commands ###
