'''add level to user school association

Revision ID: dd0527c07892
Revises: b336944a0fde
Create Date: 2025-10-08 06:25:24.020238

'''
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd0527c07892'
down_revision: Union[str, None] = 'b336944a0fde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_school_association', sa.Column('level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ALL', name='courselevelenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_school_association', 'level')
    # ### end Alembic commands ###