"""Add school_id to trading_leaderboard_snapshots

Revision ID: fd80e7d61a3e
Revises: 7ec6e7ce263a
Create Date: 2025-10-23 19:13:05.235506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd80e7d61a3e'
down_revision: Union[str, None] = '7ec6e7ce263a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_leaderboard_snapshots', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_trading_leaderboard_snapshots_school_id'), 'trading_leaderboard_snapshots', ['school_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trading_leaderboard_snapshots_school_id'), table_name='trading_leaderboard_snapshots')
    op.drop_column('trading_leaderboard_snapshots', 'school_id')
    # ### end Alembic commands ###
