from typing import Dict, Any

CACHE_TTL: Dict[str, int] = {
    "user_profile": 600,
    "user_contexts": 300,
    "user_by_email": 900,
    "courses_by_school": 300,
    "user_courses": 180,
    "course_list": 300,
    "course_details": 600,
    "school_details": 900,
    "school_students": 300,
    "school_teachers": 300,
    "school_list": 600,
    "account_balance": 60,
    "portfolio": 120,
    "watchlists": 180,
    "trade_history": 300,
    "trading_summary": 300,
    "stock_price": 30,
    "popular_stocks": 300,
    "stock_details": 600,
    "notifications_user": 120,
    "notifications_unread": 60,
    "permissions_all": 1800,
    "exam_questions": 900,
    "exam_results": 600,
    "admin_dashboard_stats": 600,
    "school_dashboard_stats": 600,
    "school_leaderboard": 300,
    "trading_leaderboard": 300,
    "course_progress": 180,
    "completed_lessons": 180,
    "lesson_progress_details": 180,
    "user_enrollments": 180,
}

CACHE_KEYS: Dict[str, str] = {
    "user_profile": "user:profile:{}",
    "user_contexts": "user:contexts:{}",
    "user_by_email": "user:by_email:{}",
    "courses_by_school": "courses:school:{}:{}:{}",
    "user_courses": "courses:user:{}:{}",
    "course_details": "course:details:{}",
    "school_details": "school:details:{}",
    "school_students": "school:students:{}:{}:{}",
    "school_teachers": "school:teachers:{}:{}:{}",
    "account_balance": "balance:user:{}",
    "portfolio": "portfolio:user:{}:{}:{}",
    "watchlists": "watchlists:user:{}:{}:{}",
    "trade_history": "trades:user:{}:{}:{}",
    "trading_summary": "trading_summary_{}",
    "stock_price": "stock:price:{}",
    "popular_stocks": "stock:popular",
    "stock_details": "stock:details:{}",
    "notifications_user": "notifications:user:{}:{}:{}",
    "notifications_unread": "notifications:unread:{}",
    "permissions_all": "permissions:all",
    "exam_questions": "exam:questions:{}",
    "exam_results": "exam:results:{}",
    "admin_dashboard_stats": "report:admin:stats",
    "school_dashboard_stats": "report:school:stats:{}",
    "school_leaderboard": "report:school:leaderboard:{}:{}:{}",
    "trading_leaderboard": "report:school:trading_leaderboard:{}:{}:{}",
    "course_progress": "progress:course:{}:user:{}",
    "completed_lessons": "progress:completed_lessons:{}:user:{}",
    "lesson_progress_details": "progress:lesson_details:{}:user:{}",
    "user_enrollments": "progress:user_enrollments:{}",
}

INVALIDATION_PATTERNS: Dict[str, Any] = {
    "user_update": [
        "user:profile:{}",
        "user:contexts:{}",
        "courses:user:{}:*",
        "balance:user:{}",
        "portfolio:user:{}:*",
        "watchlists:user:{}:*",
        "trades:user:{}:*",
        "trading_summary_{}",
        "notifications:user:{}:*",
        "notifications:unread:{}",
        "progress:course:*:user:{}",
        "progress:completed_lessons:*:user:{}",
        "progress:lesson_details:*:user:{}",
        "progress:user_enrollments:{}",
        "permissions:user:{}:school:*",
        "user:roles:{}:school:*",
    ],
    "course_update": [
        "course:details:{}",
        "courses:school:*",
        "courses:user:*",
        "exam:questions:{}",
        "exam:results:{}",
        "progress:course:{}:user:*",
        "progress:completed_lessons:{}:user:*",
        "progress:lesson_details:{}:user:*",
        "report:course_analytics:{}",
    ],
    "school_update": [
        "school:details:{}",
        "school:students:{}:*",
        "school:teachers:{}:*",
        "courses:school:{}:*",
        "report:user_activity:{}:*",
        "report:trading_leaderboard:{}",
        "report:school_performance:{}",
        "report:school:stats:{}",
        "report:school:leaderboard:{}:*",
        "report:school:trading_leaderboard:{}:*",
    ],
    "trade_execution": [
        "balance:user:{}",
        "portfolio:user:{}:*",
        "trades:user:{}:*",
        "trading_summary_{}",
        "report:trading_leaderboard:*",
    ],
    "stock_update": [
        "stock:price:{}",
        "stock:details:{}",
        "stock:popular",
        "trading:popular*",
    ],
    "admin_update": [
        "report:dashboard:admin",
        "permissions:all",
        "school:list:*",
        "popular_stocks:all:None",
    ],
}